---
#Setup docker

- name: Add docker repo
  apt_repository:
      repo: "{{ docker_repo }}"
      state: present
      mode: 0644

- name: Add docker repo key
  apt_key:
      keyserver: "{{ docker_repo_keyserver }}"
      id: "{{ docker_repo_key }}"

- name: Install docker
  apt:
      name: docker-engine
      state: latest
      force: yes
  notify: Restart docker

- name: Install docker-py
  pip:
      name: docker-py
      state: latest

- name: Install docker-compose
  pip:
    name: docker-compose
    state: latest

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes
