---
#Setup docker

- name: Install docker requirements
  apt:
      name: "{{ item }}"
      state: latest
      force: yes
  notify: Restart docker
  with_items: "{{ docker_dependencies_ubuntu }}"

- name: Add docker repo key
  apt_key:
      url: "{{ docker_repo_keyserver }}"
      state: present

- name: Add docker repo
  apt_repository:
      repo: "{{ docker_repo }}"
      state: present
      mode: 0644

- name: Install docker
  apt:
      name: docker-ce
      state: latest
      force: yes
  notify: Restart docker

- name: Install docker-compose
  pip:
    name: docker-compose
    state: present
    version: 1.9.0

- name: Create fig alias
  file:
    state: link
    src: "/usr/local/bin/docker-compose"
    path: "/usr/local/bin/fig"

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes
